config/routes.rb
Rails.application.routes.draw do
  resources :hospitals do
    member do
      post :create_doctor
      delete :delete_doctor
    end
   resources :patients do
    member do
      post :create_doctor
      delete :delete_doctor
      patch :wait
      patch :checkup
      patch :xray
      patch :surgery
      patch :pay
      patch :leave

    end
   resources :medications 
   end
 end
  

    

  root 'welcome#index'

end

app/models/medication.rb
class Medication < ActiveRecord::Base

  # belongs_to :patient
  has_many :patient_medications
  has_many :patients, through: :patient_medications
end

app/controllers/medications_controller.rb
class MedicationsController < ApplicationController


  def index
    @medications = Medication.all
    @patient = Patient.find params[:patient_id]
  end

  def show
    @patient = Patient.find params[:patient_id]
    @hospital = Hospital.find params[:hospital_id]
    @medication = Medication.find params[:id]
    @patients = @medication.patients
  end

  def new
    @medication = Medication.new
    @patients = Patient.all 
    @patient = Patient.find params[:patient_id]
    @hospital = Hospital.find params[:hospital_id]
    
  end

  def create
     @hospital = Hospital.find params[:hospital_id]
     @patient = Patient.find params[:patient_id]
     @medication = @patient.medications.new(medication_params)
      
      if @medication.save
        flash[:notice] = 'Medication was successfully perscribed.'
        redirect_to hospital_patient_path(@hospital, @patient) 
      else
        flash[:alert] = "Medication was NOT saved."
        render :new 
      end
    end
    
  def edit
    @hospital = Hospital.find params[:hospital_id]
    @patient = Patient.find params[:patient_id]
    @medication = Medication.find params [:id]
    
     
  end
# wrong num of arguments when I try to edit medication?

  def update
    @hospital = Hospital.find params[:hospital_id]
    @patient = Patient.find params[:patient_id]
    @medication = Medication.find params[:id]
    if @medication.update_attributes medication_params
      flash[:notice] = "Medication was successfully UPDATED."
      redirect_to hospital_patient_path(@hospital, @patient) 
    else
      flash[:alert] = "Medication was NOT updated."
      render :edit
    end
    
    # @medication.update medication_params
    # redirect_to medications_path
  end

  def destroy
    @hospital = Hospital.find params[:hospital_id]
    @patient = Patient.find params[:patient_id]
    @medication = Medication.find params[:id]
    @medication.delete
    redirect_to hospital_patient_path(@hospital, @patient)
  
  end

  private

  def medication_params
    params.require(:medication).permit(
      :name,
      :uses,
      :dosage,
      :side_effects,
      patient_ids: []
      )
  end

end

app/helpers/medications_helper.rb
module MedicationsHelper
end

app/views/medications/_form.html.haml
%h1 Medication form
- @medication.inspect
= form_for [@hospital, @patient, @medication] do |f|
  - if @medication.errors.any?
    - @medication.errors.full_messages.each do |message|
      = message
      %br
.div
  = form_for [@hospital, @patient, @medication] do |f|
    .form-group
      %strong= f.label :name
      = f.text_field :name, class: "form-control name_field"
      %span.error_name
        Medication name required
    %br
    .form-group
      %strong= f.label :uses
      = f.text_field :uses, class: "form-control"
      
    %br
      %strong= f.label :dosage
      = f.text_field :dosage, class: "form-control"
      
    %br
      %strong= f.label :side_effects
      = f.text_area :side_effects, class: "form-control"
      
    %br
    .div
      .checkbox
        = hidden_field_tag 'medication[patient_ids][]', ''
        - @patients.each do |patient|
          %label
          = check_box_tag 'medication[patient_ids][]', patient.id, @medication.patients.include?(patient)
          %br
          .col-md-2
            = patient.last_name
    %br
                  
      = f.submit "Submit", class: "submit_btn", disabled: 'disabled'
      = link_to "Cancel", hospital_patient_path(@hospital, @patient)

app/views/medications/edit.html.erb
<h1>edit medication</h1>

<%= render 'form' %>
<%= link_to 'Back', hospitals_patients_path(@hospital, @patient) %>

app/views/medications/index.html.erb
<h1>medication index</h1>

<ul>
  <li>
    <strong>
      <%= link_to "Edit", edit_hospital_patient_medication(medication) %>
    </strong>
    |
    <strong>
    <%= link_to "Delete", hospital_patient_medication_path(medication), method: :delete %>
    </strong>
  </li>
</ul>

<%= link_to "Back", hospitals_path %>

app/views/medications/new.html.erb
<%= render 'form' %>


<%= link_to 'Back', hospitals_path(@hospital) %>

app/views/medications/show.html.erb
<h1>Show Patient</h1> 
<br>
<strong>Name:</strong> 
<%= @patient.first_name %>
<%= @patient.last_name %>
<br>
<strong>Gender:</strong>
<%= @patient.gender %>
<br>
<strong>Date of Birth:</strong>  
<%= @patient.date_of_birth %>
<br>
<strong>Description:</strong>
<%= @patient.description %>
<br>


<%= link_to medication.name, hospital_patient_medication_path(@hospital, @patient, @medication) %>
|
<%= link_to "Edit", edit_hospital_patient_medication_path(@hospital, @patient, @medication) %>
|
<%= link_to "Delete", hospital_patient_medication_path(@hospital, @patient, @medication), method: :delete %>
<br>
<%= link_to 'Back', hospitals_path %>