config/routes.rb
Rails.application.routes.draw do
  resources :hospitals do
    member do
      post :create_doctor
      delete :delete_doctor
    end
   resources :patients do
    member do
      post :create_doctor
      delete :delete_doctor
      patch :wait
      patch :checkup
      patch :xray
      patch :surgery
      patch :pay
      patch :leave

    end
   resources :medications 
   end
 end
  

    

  root 'welcome#index'

end

app/models/patient.rb
class Patient < ActiveRecord::Base

  belongs_to :hospital
  # has_many :medications, dependent: :destroy
  has_many :patient_medications
  has_many :medications, through: :patient_medications
  has_many :doctors, as: :doctorable

  BLOOD_TYPE_OPTIONS= [
    ["A", "a"],
    ["A-", "a-"],
    ["A+", "a+"],
    ["B", "b"],
    ["B-", "b-"],
    ["B+", "b+"],
    ["AB", "ab"],
    ["AB-", "ab-"],
    ["AB+", "ab+"],
    ["O", "o"],
    ["O+", "o+"],
    ["O-", "o-"],
  ]

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :date_of_birth, presence: true
  # validates :gender, presence: true
  validates :description, presence: true
  # validates :blood_type, presence: true
  validate :at_least_10

  def at_least_10
    if self.date_of_birth
      errors.add(:date_of_birth, ':You must be at least 10 years or older') if self.date_of_birth > 10.years.ago.to_date
     
    end
  end
  
  include Workflow
    workflow do 
      state :waiting do
        event :checkup, transitions_to: :checkup
        event :xray, transitions_to: :xray
        event :surgery, transitions_to: :surgery
        event :leave, transitions_to: :leaving 
      end
      state :checkup do
        event :wait, transitions_to: :waiting
        event :xray, transitions_to: :xray
        event :surgery, transitions_to: :surgery
        event :pay, transitions_to: :paying
      end
      state :xray do
        event :wait, transitions_to: :waiting
        event :checkup, transitions_to: :checkup
        event :surgery, transitions_to: :surgery
        event :pay, transitions_to: :paying
      end
      state :surgery do
        event :wait, transitions_to: :waiting
        event :xray, transitions_to: :xray
        event :checkup, transitions_to: :checkup
        event :pay, transitions_to: :paying
      end
      state :paying do
        event :leave, transitions_to: :leaving
      end

      state :leaving
      end
end

      

  

  

   

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
# list only what excepts an id
  before_action :set_patient, only: [
    :show,
    :edit,
    :update,
    :destroy,
    :wait,
    :checkup,
    :xray,
    :surgery,
    :pay,
    :leave
  ]

  def index
    @patients = Patient.all
    @hospital = Hospital.find params[:hospital_id]
  end

  def show
    @hospital = Hospital.find params[:hospital_id]
    @patient = Patient.find params[:id]
    @medications = if !params[:q].blank?
      @patient.medications.where("name LIKE ? OR uses LIKE ? OR dosage LIKE ?", "%#{params[:q]}%", "%#{params[:q]}%", "%#{params[:q]}%")
    else
      @patient.medications
    end
    @doctor = Doctor.new
    @doctors = @patient.doctors
  end

  def new
    @patient = Patient.new
    @hospital = Hospital.find params[:hospital_id]
    # added @medication = Medication.all 1/26 for join table
    @medications = Medication.all
  end

  def create
    @hospital = Hospital.find params[:hospital_id]
    @patient = @hospital.patients.new(patient_params)
    # added @medication = Medication.all 1/26 for join table
    @medications = Medication.all

    if @patient.save
      flash[:notice] = "Patient was successfully created."
      redirect_to hospital_path(@hospital)
    else
      flash[:alert] = "Patient was NOT saved."
      render :new
    end
  end

  def create_doctor
    @hospital = Hospital.find params[:hospital_id]
    @patient = Patient.find params[:id]
    @patient.doctors.create doctor_params
    redirect_to hospital_patient_path(@hospital, @patient)
  end

  def delete_doctor
    @hospital = Hospital.find params[:hospital_id]
    @patient = @hospital.patients.find params[:id]
    @doctor = @patient.doctors.find params[:doctor_id]
    @doctor.delete
    redirect_to hospital_patient_path(@hospital, @patient)
  end
    
  def edit
    @hospital = Hospital.find params[:hospital_id]
    @patient = Patient.find params[:id]
    # added for join table
    @medications = @patient.medications
    
  end

  def update
    # added for join table
    @medications = Medication.all
    @hospital = Hospital.find params[:hospital_id]
    @patient = Patient.find params[:id]
    if @patient.update_attributes patient_params
      flash[:notice] = "Patient was successfully UPDATED."
      redirect_to hospital_patient_path(@hospital, @patient)
    else 
      flash[:alert] = "Patient was NOT updated."
      render :edit
    end
  end

  def destroy
    @hospital = Hospital.find params[:hospital_id]
    @patient = Patient.find params[:id]
    @patient.delete
    redirect_to hospital_patients_path(@hospital)
  end

  def wait
    @hospital = Hospital.find params[:hospital_id]
    @patient = Patient.find params[:id]
    @patient.wait!
    respond_to do |format|
      format.js
      format.html
    end
  end

  def checkup
    @hospital = Hospital.find params[:hospital_id]
    @patient = Patient.find params[:id]
    @patient.checkup!
    respond_to do |format|
        format.js
        format.html
      end
  end

  def xray
    @hospital = Hospital.find params[:hospital_id]
    @patient = Patient.find params[:id]
    @patient.xray!
    respond_to do |format|
        format.js
        format.html
      end
  end

  def surgery
    @hospital = Hospital.find params[:hospital_id]
    @patient = Patient.find params[:id]
    @patient.surgery!
    respond_to do |format|
        format.js
        format.html
      end
  end

  def pay
    @hospital = Hospital.find params[:hospital_id]
    @patient = Patient.find params[:id]
    @patient.pay!
    respond_to do |format|
        format.js
        format.html
      end

  end

  def leave
    @hospital = Hospital.find params[:hospital_id]
    @patient = Patient.find params[:id]
    @patient.leave!
    respond_to do |format|
        format.js
        format.html
      end
  end

private
   
  def find_patient
    @patient = Patient.find params[:id]
  end

  def patient_params
    params.require(:patient).permit(
      :first_name,
      :last_name,
      :date_of_birth,
      :gender,
      :description,
      :blood_type,
      medication_ids: []
    )
  end
  def medication_params
    params.require(:medication).permit(
      :name,
      :uses,
      :dosage,
      :side_effects,
      patient_ids: []
      )
  
  end

  def doctor_params
    params.require(:doctor).permit(:doctor_name)  
  end

  def set_patient
    @patient = Patient.find(params[:id])
  end

end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_form.html.haml
.col-md-6.col-md-offset-3
  .text-left
    = form_for [@hospital, @patient] do |f|
      - if @patient.errors.any?
        - @patient.errors.full_messages.each do |message|
          = message
          %br
.col-md-6.col-md-offset-3
  .text-left
    = form_for [@hospital, @patient] do |f|
      .form-group
        %strong= f.label :first_name
        = f.text_field :first_name, class: "form-control name_field"
        %span.error_first_name
          First name required
      .form-group
        %strong= f.label :last_name
        = f.text_field :last_name, class: "form-control name_field"
        %span.error_last_name
          Last name required
      %br
      .form-group
        = f.label :date_of_birth
        = f.date_field :date_of_birth, :start_year => Date.today.year - 100, :end_year => Date.today.year, class: "form-control"
        %span.error_date_of_birth
          Date of Birth required
      %br
        = f.label :gender
        = f.radio_button(:gender, "male")
        = f.label(:gender, "male")
        = f.radio_button(:gender, "female")
        = f.label(:gender, "female")
      %br
      .form-group
        = f.label :description
        = f.text_field :description, class: "form-control"
      %br
        = f.label :blood_type
        = f.select :blood_type, options_for_select(Patient::BLOOD_TYPE_OPTIONS, f.object.blood_type), include_blank: "---Select---"
      %br
      .col-md-12
        
        .checkbox
          = hidden_field_tag 'patient[medication_ids][]', ''
          - @medications.each do |medication|
            %label
              .col-md-6
                = check_box_tag 'patient[medication_ids][]', medication.id, @patient.medications.include?(medication)
                .col-md-6
                  = medication.name

      %br
        = f.submit "Submit", class: "submit_btn", disabled: 'disabled'
        = link_to "Cancel", hospital_path(@hospital)

app/views/patients/_workflow.html.haml
.workflow{class: "workflow-#{patient.id}"}
  = patient.workflow_state
  %br
    - if patient.waiting?
      = link_to "Checkup", 'javascript:void(0);', class: "checkup", hospital_id: @hospital.id, patient_id: patient.id
      = link_to "Xray", 'javascript:void(0);', class: "xray", hospital_id: @hospital.id, patient_id: patient.id
      = link_to "Surgery", 'javascript:void(0);', class: "surgery", hospital_id: @hospital.id, patient_id: patient.id
      = link_to "Leaving", 'javascript:void(0);', class: "leave", hospital_id: @hospital.id, patient_id: patient.id
      = link_to "Pay bill", 'javascript:void(0);', class: "paying", hospital_id: @hospital.id, patient_id: patient.id
    - if patient.checkup?
      = link_to "Waiting", 'javascript:void(0);', class: "wait", hospital_id: @hospital.id, patient_id: patient.id
      = link_to "Xray", 'javascript:void(0);', class: "xray", hospital_id: @hospital.id, patient_id: patient.id
      = link_to "Surgery", 'javascript:void(0);', class: "surgery", hospital_id: @hospital.id, patient_id: patient.id
      = link_to "Pay bill", 'javascript:void(0);', class: "paying", hospital_id: @hospital.id, patient_id: patient.id
    -if patient.xray?
      = link_to "Waiting", 'javascript:void(0);', class: "waiting", hospital_id: @hospital.id, patient_id: patient.id
      = link_to "Checkup", 'javascript:void(0);', class: "checkup", hospital_id: @hospital.id, patient_id: patient.id
      = link_to "Surgery", 'javascript:void(0);', class: "surgery", hospital_id: @hospital.id, patient_id: patient.id
      = link_to "Pay bill", 'javascript:void(0);', class: "paying", hospital_id: @hospital.id, patient_id: patient.id
    -if patient.surgery?
      = link_to "Waiting", 'javascript:void(0);', class: "waiting", hospital_id: @hospital.id, patient_id: patient.id
      = link_to "Xray", 'javascript:void(0);', class: "xray", hospital_id: @hospital.id, patient_id: patient.id
      = link_to "Checkup", 'javascript:void(0);', class: "checkup", hospital_id: @hospital.id, patient_id: patient.id
      = link_to "Pay bill", 'javascript:void(0);', class: "paying", hospital_id: @hospital.id, patient_id: patient.id
    -if patient.paying?
      = link_to "Leaving", 'javascript:void(0);', class: "leave", hospital_id: @hospital.id, patient_id: patient.id

app/views/patients/checkup.js.haml
$(".workflow-#{@patient.id}").html("#{j(render 'hospitals/workflow', patient: @patient)}");

app/views/patients/edit.html.haml
.col-md-6.col-md-offset-3
= render 'form'
%br
.col-md-6.col-md-offset-3  
  = link_to 'Back', hospitals_path(@hospital)

 

app/views/patients/index.html.haml
.col-md-6.col-md-offset-3
  = link_to "Welcome", hospitals_path
  |
  = link_to @hospital.name, hospital_path(@hospital)
  .text-center
    %h2
      Patient Workflow
    
    = link_to "Create Patient", new_hospital_patient_path(@hospital)
.col-md-12
  .text-center
    - @patients.each do |patient|
      .col-md-6.col-md-offset-3
        .list-group-item
          .text-center
            %strong 
            = link_to patient.first_name, hospital_patient_path(@hospital, patient)
            = link_to patient.last_name, hospital_patient_path(@hospital, patient)
            %br 
            = patient.gender
            = patient.date_of_birth.strftime("%m/%d/%Y")
            %br
            = patient.description
          %strong
            .workflow{class: "workflow-#{patient.id}"}
              = render 'workflow', patient: patient

              
    
    

app/views/patients/leave.js.haml
$(".workflow-#{@patient.id}").html("#{j(render 'hospitals/workflow', patient: @patient)}");

app/views/patients/new.html.haml
%h1 New Patient

= render 'form'

= link_to 'Back', hospitals_path(@hospital)

app/views/patients/pay.js.haml
$(".workflow-#{@patient.id}").html("#{j(render 'hospitals/workflow', patient: @patient)}");

app/views/patients/show.html.haml
.col-md-6.col-md-offset-3
  = link_to "Welcome", hospitals_path
  |
  = link_to @hospital.name, hospital_path(@hospital)
.col-md-12.col-lg-12
  .text-left
  %h3= @hospital.name
  %div
    = @hospital.address
    %div
      
    = @hospital.city
    ,
    = @hospital.state
    = @hospital.zip
    %div
    = @hospital.phone
  .text-center
    %h3
      Patient Information Page
.col-md-6.col-md-offset-3
  .text-center
    %h4
      = @patient.first_name
      = @patient.last_name
      %div
    Date of Birth: #{@patient.date_of_birth.strftime("%m/%d/%Y")}
    %br
    Gender: #{@patient.gender}
    %br
    %strong
      Reason for visit:  #{@patient.description}

.col-md-12.col-lg-12
  .list-group-item 
    .text-center
      %strong 
        %h4
          Patient Medications:
    .col-md-12.col-lg-12   
      .text-left
        = form_tag hospital_patient_path, method: :get, class: "navbar-form", role: "search" do
          .input-group
            = text_field_tag 'q', params[:q], class: "form-control", id: "srch-term", placeholder: "Search Medications"
            .input-group-btn
              %button.btn.btn-default{:style => "width:40px;"}
                %i.glyphicon.glyphicon-search
    .col-md-12.col-lg-12
      .text-center
        - @medications.each do |medication|
          %strong 
            = medication.name
          %li 
            %strong Used for:
            = medication.uses
          %li
            %strong Dosage:
            = medication.dosage
          %li
            %strong Side Effects:
            = medication.side_effects
              
          %br
        = link_to "Add Medication", new_hospital_patient_medication_path(@hospital, @patient)
.col-md-12.col-lg-12
  .text-center
    %strong 
      %h4
        Patient Doctor(s): 
.col-md-12.col-lg-12
  .list-group-item
    .text-center      
      - @doctors.each do |doctor|
        %li
          = doctor.doctor_name
          = link_to "Delete Doctor", delete_doctor_hospital_patient_path(@patient, doctor), method: :delete
        %br
 
        = form_for @doctor, url: create_doctor_hospital_patient_path(@hospital, @patient) do |f|
          .form_group
            = f.label :doctor_name
            = f.text_area :doctor_name
            
            = f.submit "Add Doctor"
        
.col-md-12.col-lg-12
 
  .text-center            

    = link_to "Edit Patient", edit_hospital_patient_path(@hospital, @patient)
    |
    = link_to "Delete Patient", hospital_patient_path(@hospital, @patient), method: :delete
    |
    = link_to 'Back to Hospitals List', hospitals_path



              
      

app/views/patients/surgery.js.haml
$(".workflow-#{@patient.id}").html("#{j(render 'hospitals/workflow', patient: @patient)}");

app/views/patients/wait.js.haml
$(".workflow-#{@patient.id}").html("#{j(render 'hospitals/workflow', patient: @patient)}");

app/views/patients/xray.js.haml
$(".workflow-#{@patient.id}").html("#{j(render 'hospitals/workflow', patient: @patient)}");