config/routes.rb
Rails.application.routes.draw do
  resources :hospitals do
    member do
      post :create_doctor
      delete :delete_doctor
    end
   resources :patients do
    member do
      post :create_doctor
      delete :delete_doctor
      patch :wait
      patch :checkup
      patch :xray
      patch :surgery
      patch :pay
      patch :leave

    end
   resources :medications 
   end
 end
  

    

  root 'welcome#index'

end

app/models/hospital.rb
class Hospital < ActiveRecord::Base

  has_many :patients, dependent: :destroy
  has_many :doctors, as: :doctorable

  STATE_OPTIONS= [
    ["Alabama", "AL"],
    ["Alaska", "AK"],
    ["Arizona", "AZ"],
    ["Arkansas", "AR"],
    ["California", "CA"],
    ["Colorado", "CO"],
    ["Connecticut", "CT"],
    ["Delaware", "DE"],
    ["Florida", "FL"],
    ["Georgia", "GA"],
    ["Hawaii", "HI"],
    ["Idaho", "ID"],
    ["Illinois", "IL"],
    ["Indiana", "IN"],
    ["Iowa", "IA"],
    ["Kansas", "KS"],
    ["Kentucky", "KY"],
    ["Louisiana", "LA"],
    ["Maine", "ME"],
    ["Maryland", "MD"],
    ["Massachusetts", "MA"],
    ["Michigan", "MI"],
    ["Minnesota", "MN"],
    ["Mississippi", "MS"],
    ["Missouri", "MO"],
    ["Montana", "MT"],
    ["Nebraska", "NE"],
    ["Nevada", "NV"],
    ["New Hampshire", "NH"],
    ["New Mexico", "NM"],
    ["New York", "NY"],
    ["North Carolina", "NC"],
    ["North Dakota", "ND"],
    ["Ohio", "OH"],
    ["Oklahoma", "OK"],
    ["Oregon", "OR"],
    ["Pennsylvania", "PA"],
    ["Rhode Island", "RI"],
    ["South Carolina", "SC"],
    ["South Dakota", "SD"],
    ["Tennessee", "TN"],
    ["Texas", "TX"],
    ["Utah", "UT"],
    ["Vermont", "VT"],
    ["Virginia", "VA"],
    ["Washington", "WA"],
    ["West Virginia", "WV"],
    ["Wisconsin", "WI"],
    ["Wyoming", "WY"]
  ]
  

end

app/controllers/hospitals_controller.rb
class HospitalsController < ApplicationController
  # before_action :set_hospital, only: [:show, :edit, :update, :destroy]
  def index
    @hospitals = if !params[:q].blank?
      Hospital.where("name LIKE ? OR address LIKE ? OR city LIKE ? OR state LIKE ?", "%#{params[:q]}%", "%#{params[:q]}%", "%#{params[:q]}%", "%#{params[:q]}%")
    else
      @hospitals = Hospital.all
    end
  end

  
  def show
    @hospital = Hospital.find params[:id]
    @patients = if !params[:q].blank?
      @hospital.patients.where("first_name LIKE ? OR last_name LIKE ? OR date_of_birth LIKE ? OR description LIKE ? OR gender LIKE ? OR blood_type LIKE ? OR workflow_state LIKE ?", "%#{params[:q]}%", "%#{params[:q]}%", "%#{params[:q]}%", "%#{params[:q]}%", "%#{params[:q]}%", "%#{params[:q]}%", "%#{params[:q]}%")
    else
      @hospital.patients
    end
    @doctor = @hospital.doctors.new
  end


  def new
    @hospital = Hospital.new
  end

  # def create
  #   @hospital = Hospital.create hospital_params
  #   redirect_to hospitals_path
  # end

  def create
    @hospital = Hospital.create hospital_params
    if @hospital.save
      flash[:notice] = 'Hospital was successfully created'
      redirect_to @hospital
    else
      flash[:alert] = "Hospital was NOT saved"
      render :new
    end
  end

  def create_doctor
    @hospital = Hospital.find params[:id]
    @hospital.doctors.create doctor_params
    redirect_to hospital_path(@hospital)
  end

  def delete_doctor
    @hospital = Hospital.find params[:id]
    @doctor = Doctor.find params[:doctor_id]
    @doctor.delete
    redirect_to hospital_path
  end

  def edit
    @hospital = Hospital.find params[:id]
  end

  def update
    @hospital = Hospital.find params[:id]
    @hospital.update_attributes hospital_params
    if @hospital.update_attributes hospital_params
      flash[:notice] = "Patient was successfully UPDATED."
      redirect_to hospitals_path
    else
      flash[:alert] = "Patient was NOT updated."
      render :edit
    end

  end

  def destroy
    @hospital = Hospital.find params[:id]
    @hospital.delete
    redirect_to hospitals_path
  end

  private

  def hospital_params
    params.require(:hospital).permit(
      :name,
      :address,
      :city,
      :state,
      :zip,
      :phone
      )
  end
  
  def find_patient
    @patient = Patient.find params[:id]
  end

  def doctor_params
    params.require(:doctor).permit(:doctor_name)
  end
end


  

app/helpers/hospitals_helper.rb
module HospitalsHelper
end

app/views/hospitals/_form.html.haml
%h1 Hospital form
- @hospital.inspect
%br
  = form_for @hospital do |f|
    - if @hospital.errors.any?
      - @hospital.errors.full_messages.each do |message|
        = message
        %br
  .div
    = form_for [@hospital] do |f|
      .form-group
        %strong= f.label :name
        = f.text_field :name, class: "form-control"
        %span.error_name
          Name required
      .form-group
        %strong= f.label :address
        = f.text_field :address, class: "form-control"
      %br
      .form-group
        = f.label :city
        = f.text_field :city, class: "form-control"
      %br
      .form-group      
        = f.label :state
        = f.select :state,options_for_select( Hospital:: STATE_OPTIONS, f.object.state), include_blank: "---select---" |
      %br         
        = f.label :zip
        = f.text_field :zip
      %br
                      
        = f.label :phone
        = f.text_field :phone
      %br
        = f.submit "Submit", class: "submit_btn", disabled: 'disabled'
      
        = link_to "Cancel", root_path


                         
      
       

app/views/hospitals/_workflow.html.haml
= patient.workflow_state
%br
  - if patient.waiting?
    = link_to "Checkup", 'javascript:void(0):', class: "checkup", hospital_id: @hospital.id, patient_id: patient.id
    = link_to "Xray", 'javascript:void(0):', class: "xray", hospital_id: @hospital.id, patient_id: patient.id
    = link_to "Surgery", 'javascript:void(0):', class: "surgery", hospital_id: @hospital.id, patient_id: patient.id
    = link_to "Leaving", 'javascript:void(0):', class: "leave", hospital_id: @hospital.id, patient_id: patient.id
  - if patient.checkup?
    = link_to "Waiting", 'javascript:void(0):', class: "wait", hospital_id: @hospital.id, patient_id: patient.id

app/views/hospitals/edit.html.haml
%h1 Edit Hospital
= render 'form'
= link_to 'Show', @hospital
|
=link_to 'Back', hospitals_path

app/views/hospitals/index.html.haml
/ url= localhost:3000/hospitals
%div.col-sm-3.col-md-6.col-lg-12
  .text-left
    %button.create_hospital
      = link_to "Create Hospital", new_hospital_path, class: "stylebutton"

%div.search
  
  = form_tag hospitals_path, method: :get, class: "navbar-form", role: "search" do
    .input-group
      = text_field_tag 'q', params[:q], class: "form-control", id: "srch-term", placeholder: "Search"
      .input-group-btn
        %button.btn.btn-default{:style => "width:40px;"}
          %i.glyphicon.glyphicon-search
.row
- x = 0
- y = 1
%ul{class: "hospital_list"}     
  - @hospitals.each_slice(6) do |row|
    %li{class: "section_#{x+1}"}
      - x = x + 1
      - row.each do |hospital|
        .imgOut
          .hospital_list
            %h4
            
              = link_to hospital[:name], hospital_path(hospital)
          
            = hospital[:address]
            %br
            = hospital[:city] 
            ,
            = hospital[:state]
            %br
            = hospital[:zip]
            %br
            = link_to "Edit", edit_hospital_path(hospital), class: "btn btn-danger"
            
            = link_to "delete", hospital_path(hospital), method: :delete, class: "btn btn-danger"
        

.col-md-12
  - x.times do
    %a{class: "page_#{y}", num: y}
      = " #{y}" 
       
      = "|"
    - y += 1
  %br
  %br  

app/views/hospitals/new.html.haml
= render 'form' 

= link_to 'Back', hospitals_path 

app/views/hospitals/show.html.haml
.container
  .text-left
    = link_to 'Back to hospital main page', hospitals_path
.container
  .text-left
    = form_tag hospital_path, method: :get, class: "navbar-form", role: "search" do
      .input-group
        = text_field_tag 'q', params[:q], class: "form-control", id: "srch-term", placeholder: "Search Patients"
        .input-group-btn
          %button.btn.btn-default{:style => "width:40px;"}
            %i.glyphicon.glyphicon-search


  .container
    .text-left
    %h3= @hospital.name
    %div
      = @hospital.address
      %div
        
      = @hospital.city
      ,
      = @hospital.state
      = @hospital.zip
      %div
      = @hospital.phone
    %br
    %div
    = link_to "Create Patient", new_hospital_patient_path(@hospital)

.container
  / .list-group-item.workflow
  .text-center
    %h4.patient
      .text-uppercase
      = link_to "Patient Workflow", hospital_patients_path(@hospital), class: "btn btn-danger"

  - @patients.each do |patient|
    .list-group-item.workflow
      .text-center
        %strong 
          = link_to patient.first_name, hospital_patient_path(@hospital, patient)
          = link_to patient.last_name, hospital_patient_path(@hospital, patient)
          = patient.date_of_birth.strftime("%m/%d/%Y")
%br

.container.doctors
  .text-center.doctor1
    %u
      %h4 Doctors associated with hospital:
    / will show the doctor that goes with that hospital
  / .list-group-item.form
  .text-center
    = form_for @doctor, url: create_doctor_hospital_path(@hospital) do |f|
      - @hospital.doctors.each do |doctor|
        - if doctor.id
          = doctor.doctor_name
          |
          = link_to "Delete Doctor", delete_doctor_hospital_path(@hospital, doctor_id: doctor.id), method: :delete
          %br
      %div.doctors
        %br
          = f.label :doctor_name
          = f.text_field :doctor_name
           
          = f.submit "submit new doctor", class: "btn btn-primary"
          
   
  